name: Terraform Deploy & Ansible Configure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Capture Terraform Outputs
      id: tfoutputs
      run: |
        echo "NGINX_IP=$(terraform output -raw nginx_public_ip)" >> $GITHUB_ENV
        echo "JAVA_IP=$(terraform output -raw java_public_ip)" >> $GITHUB_ENV

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ec2.pem
        chmod 400 ~/.ssh/ec2.pem

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Create Ansible Inventory
      run: |
        cat <<EOF > inventory.ini
        [nginx]
        $NGINX_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2.pem

        [java]
        $JAVA_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2.pem
        EOF

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini playbook.yml

    # OPTIONAL – uncomment if you want auto destroy
    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve
